name: CD
on: [push, workflow_dispatch]
jobs:
  deploy:
    name: Apply changes to the server
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && 'refs/head/main'
    steps:
      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/aws
          chmod 600 ~/.ssh/aws
          cat >>~/.ssh/config <<END
          Host kamuridesu.tech
            HostName kamuridesu.tech
            User admin
            IdentityFile ~/.ssh/aws
            StrictHostKeyChecking no
          END
        env:
            SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      - name: Clone or update repository
        run: ssh admin@kamuridesu.tech "cd ${{ github.event.repository.name }} && git pull || git clone https://github.com/${{ github.repository }}.git"
      - name: Backup config
        run: ssh admin@kamuridesu.tech "cp /etc/haproxy/haproxy.cfg ./haproxy.cfg.backup"
      - name: Put files on server
        run: |
          ssh admin@kamuridesu.tech "USERNAME=${{ secrets.USERNAME }}; PASSWORD=${{ secrets.PASSWORD }}; sudo cat ${{ github.event.repository.name }}/haproxy.cfg | sudo envsubst > /etc/haproxy/haproxy.cfg"
      - name: Restart HAProxy
        run: ssh admin@kamuridesu.tech "sudo /etc/init.d/haproxy restart"
