name: CD
on: [push, workflow_dispatch]
jobs:
  deploy:
    name: Apply changes to the server
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && 'refs/head/main'
    steps:
      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/aws
          chmod 600 ~/.ssh/aws
          cat >>~/.ssh/config <<END
          Host $IP_ADDR
            HostName $IP_ADDR
            User $USERNAME
            IdentityFile ~/.ssh/aws
            StrictHostKeyChecking no
          END
        env:
            SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
            IP_ADDR: ${{ secrets.IP_ADDR }}
            USERNAME: ${{ secrets.SERVER_USER }}
      - name: Clone or update repository
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.IP_ADDR }} "cd ${{ github.event.repository.name }} && git pull || git clone https://github.com/${{ github.repository }}.git"
      - name: Backup config
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.IP_ADDR }} "cp /etc/haproxy/haproxy.cfg ./haproxy.cfg.backup"
      - name: Validate configuration
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.IP_ADDR }} "export USERNAME=${{ secrets.USERNAME }}; export PASSWORD=${{ secrets.PASSWORD }}; export BACKEND_IP_ADDR=${{ secrets.BACKEND_IP_ADDR }}; cat ${{ github.event.repository.name }}/haproxy.cfg | envsubst > /tmp/haproxy.cfg"
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.IP_ADDR }} "echo '' >> /tmp/haproxy.cfg; haproxy -c -f /tmp/haproxy.cfg"
      - name: Update config file
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.IP_ADDR }} "echo '' >> /tmp/haproxy.cfg; sudo cp /tmp/haproxy.cfg /etc/haproxy/haproxy.cfg"
      - name: Restart HAProxy
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.IP_ADDR }} "sudo /etc/init.d/haproxy restart"
